
package:
    name: wxpython
    version: 3.0.2.0

source:
    fn: wxPython-src-3.0.2.0.tar.bz2
    url: http://downloads.sourceforge.net/wxpython/wxPython-src-3.0.2.0.tar.bz2
    sha1: 5053f3fa04f4eb3a9d4bfd762d963deb7fa46866

build:
    number: 0

requirements:
  host:
    - python =2
  run:
    - python =2

test:
    imports:
        - wx

about:
    home: http://www.wxpython.org
    license: wxWindows Licese
